### ISSUE TITLE
dlfcn.h make error

### ISSUE THREAD

**Issue by bxff** [dark/dropbox-filesystem-fix#12]
The title says it all, 
it asks to unlink one of my device usually the same one I am using and adding it again, very annoying, please help.

**Comment by bxff** [comment]
also tiring again it doesn't open Dropbox, log file:

```
bn.BUILD_KEY: Dropbox
bn.VERSION: 81.4.195
bn.DROPBOXEXT_VERSION: failed
bn.is_frozen: True
machine_id: ea7fe852-4e4c-45ea-a679-c2cc4b962f54
pid: 3091
ppid: 1713
ppid exe: '/usr/lib/systemd/systemd'
uid: 0
user_info: pwd.struct_passwd(pw_name='root', pw_passwd='x', pw_uid=0, pw_gid=0, pw_gecos='root', pw_dir='/root', pw_shell='/bin/bash')
effective_user_info: pwd.struct_passwd(pw_name='root', pw_passwd='x', pw_uid=0, pw_gid=0, pw_gecos='root', pw_dir='/root', pw_shell='/bin/bash')
euid: 0
gid: 0
egid: 0
group_info: grp.struct_group(gr_name='root', gr_passwd='x', gr_gid=0, gr_mem=[])
effective_group_info: grp.struct_group(gr_name='root', gr_passwd='x', gr_gid=0, gr_mem=[])
LD_LIBRARY_PATH: None
cwd: '/root'
     real_path='/root'
           	mode=0o40755	uid=0	gid=0
     parent	mode=0o40755	uid=0	gid=0
HOME: '/root'
appdata: '/root/.dropbox/instance1'
         real_path='/root/.dropbox/instance1'
               	mode=0o40700	uid=0	gid=0
         parent	mode=0o40755	uid=0	gid=0
dropbox_path: '/root/Dropbox'
              real_path='/root/Dropbox'
                    	mode=0o40700	uid=0	gid=0
              parent	mode=0o40755	uid=0	gid=0
sys_executable: '/root/.dropbox-dist/dropbox-lnx.x86_64-81.4.195/dropbox'
                real_path='/root/.dropbox-dist/dropbox-lnx.x86_64-81.4.195/dropbox'
                      	mode=0o100775	uid=1000	gid=1000
                parent	mode=0o40775	uid=1000	gid=1000
trace.__file__: '/root/.dropbox-dist/dropbox-lnx.x86_64-81.4.195/python-packages-37.zip/dropbox/client/ui/common/boot_error.pyc'
                real_path='/root/.dropbox-dist/dropbox-lnx.x86_64-81.4.195/python-packages-37.zip/dropbox/client/ui/common/boot_error.pyc'
                      	not found
                parent	not found
tempdir: '/tmp'
         real_path='/tmp'
               	mode=0o41777	uid=0	gid=0
         parent	mode=0o40755	uid=0	gid=0
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 784, in wrapper
  File "dropbox/client/main.pyc", line 6257, in finish_dropbox_boot
  File "dropbox/client/main.pyc", line 5761, in _init_components_for_account
  File "dropbox/sync_engine_boundary/factory.pyc", line 328, in make_sync_engine
  File "dropbox/sync_engine/nucleus/classic_client/sync_engine.pyc", line 391, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 208, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 569, in _init_new_engine_locked
  File "dropbox/sync_engine/nucleus/thin_client/client.pyc", line 129, in __init__
  File "nucleus_python.pyx", line 85, in nucleus_python.NucleusSyncEngine.__cinit__
nucleus_python.SyncEngineError: Initializing engine |>> Initializing platform |>> Checking if filesystem is supported |>> Filesystem is not supported: "Unknown(2035054128)"
```

**Comment by bxff** [comment]
Another problem it pops up for a folder rename or chose which folder, whenever I will chose rename it renames old folder 'Dropbox(old)' and create a not folder and literally stops, doesn't do anything, but does say Dropbox is running when tried running again. Also I am using Kali 2019 is case that is impotent.

**Comment by dark** [comment]
Hi, by looking at the log you pasted, it seems like you are spawning dropbox from systemd. I have no experience about systemd so I cannot give you direct advice.

Given the symptoms, possible causes include:
* systemd is not setting LD_PRELOAD, like dropbox_start.py does. The workaround won't work if the library is not loaded.
* version 81.4.195 is newer than the latest version I tested. The workaround might have stopped working due to changes in the client code.

**Comment by bxff** [comment]
When running the 'make', I get this error:
it's coming from the dlfcn.h, I googled a bit but couldn't find much, is there a suggestion on what I should do next? also, I am using GCC-9, should I use an older version?
```
gcc -shared -fPIC -Wall -o libdropbox_fs_fix.so libdropbox_fs_fix.c -ldl
In file included from libdropbox_fs_fix.c:21:
/usr/include/dlfcn.h:183:3: internal compiler error: Segmentation fault
  183 |   Dl_serpath dls_serpath[1]; /* Actually longer, dls_cnt elements.  */
      |   ^~~~~~~~~~
0x7f31404a80ff ???
	/build/glibc-9T0kFa/glibc-2.29/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f3140494bba __libc_start_main
	../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
make: *** [Makefile:36: libdropbox_fs_fix.so] Error 1

```

**Comment by bxff** [comment]
Ok, So I installed a fresh version of kali on the WinStore(Just for checking) and the make file had no problems compiling, though the dropbox_start didn't work as I didn't have dropbox installed on my kali, so I installed and I started flawlessly thought its useless as my Win is running on a filesystem that supports dropbox officially, I will close once I will reinstall my kali from scratch and check if then its working or not.

This problem was cassed by the OS or C++ program and not the code 👍  @dark
